DELTA-805 add contexts sdk
Smartling/java-api-sdk pull request #61
Opened 2021-06-15 10:54 UTC by MihailTymoshenko

Replace this text with a description of your proposed change.

[JIRA Ticket](https://bt.smartling.net/browse/DELTA-805)

## Squash Commit Guidelines

This is a reminder on how to format your sqaush commit message. Delete from your PR after noting below.

### Message Header

`feat: add Contexts API`

#### Subject Text

Add Contexts API

2021-06-23 16:41 UTC, vbarhatov requested changes

2021-06-25 08:00 UTC, MihailTymoshenko commented on smartling-contexts-api/src/test/java/com/smartling/api/contexts/v2/ContextsApiTest.java
> +        "          \"bindingUid\": \"bindingId1\",\n" +
done

2021-06-25 08:10 UTC, MihailTymoshenko commented on smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/MatchStatusPTO.java
> +    private String contextId;
done

2021-06-25 08:10 UTC, MihailTymoshenko commented on smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/pto/BatchDeleteBindingsRequestPTO.java
> +    private boolean notifyTms;
done

2021-06-25 08:10 UTC, MihailTymoshenko commented on smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/ContextsApi.java
> +        @MultipartForm HtmlContextUploadAndMatchPTO contextUploadPTO);
fixed

2021-06-25 08:10 UTC, MihailTymoshenko commented on smartling-contexts-api/src/main/java/com/smartling/api/contexts/v2/ContextsApi.java
> +    void deleteBinding(@PathParam("projectId") String projectId, @PathParam("bindingUid") String bindingUid);
fixed

2021-06-30 10:59 UTC, vbarhatov approved these changes

2021-06-30 11:44 UTC, AlexArcher approved these changes

2021-06-30 12:02 UTC, merged